version: "3.7"
services:
  bot:
    container_name: easterobot_bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./easterobot/data/config.yml:/app/easterobot/data/config.yml
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - logs:/app/easterobot/data/logs

volumes:
  logs:
