exclude: '^(\.tox|\.mypy|\.git)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
      - id: check-json
      - id: check-toml
  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.287"
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.4.1"
    hooks:
      - id: mypy
        pass_filenames: false
        args: ["."]
        additional_dependencies:{%- if "click" == cookiecutter.cli %}
          - "click>=8.1.0"{%- endif %}
          - "pytest==7.4.2"
          - "pytest-mock==3.11.1"
          - "typing-extensions>=4.7.1"
          - "types-setuptools==68.2.0.0"
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf
        exclude: "(\\.bat|\\.cmd|\\.ps1)$"
