version: "3.7"
services:
  {{ cookiecutter.__project_slug }}:
    container_name: {{ cookiecutter.__project_slug }}
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - {{ cookiecutter.__project_slug }}
    volumes:
      # Use computer time
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  {{ cookiecutter.__project_slug }}:
    driver: bridge

volumes:
  logs:
