exclude: '^(\.tox|\.mypy|\.git)(/|$)'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.265'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
      - id: mypy
        pass_filenames: false
        args: ["."]
        additional_dependencies:{%- if "click" == cookiecutter.cli %}
          - "click>=8.1.0"{%- endif %}
          - "typing-extensions>=4.5.0"
          - "pytest>=7.3.0"
          - "pytest-mock>=3.10.0"
          - "mypy>=1.2.0"
          - "black>=23.0.0"
          - "ruff>=v0.0.265"
          - "types-setuptools>=57.0"
