version: "3.7"
services:
  {{ cookiecutter.__pypi_name }}:
    container_name: {{ cookiecutter.__pypi_name }}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
